# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# 1. Specify Node.js Version (e.g., Node 20 LTS on Alpine)
FROM node:20-alpine

# Create a non-root user and group
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json with correct ownership
COPY --chown=appuser:appgroup package*.json ./

# Install dependencies as root temporarily for global cache, then prune devDependencies
# Or, install as appuser if no global packages are needed and to keep permissions clean
# For simplicity and security, let's try installing as appuser directly if it works.
# If npm needs root for some global actions even with --ignore-scripts, we might need a multi-stage build
# or more complex permission handling.
# RUN npm install --ignore-scripts
# Switching to appuser before npm install to avoid running npm as root for project dependencies
USER appuser
RUN npm install --ignore-scripts --omit=dev # Omit dev dependencies for production

# Copy the rest of the application files with correct ownership
# Note: If WORKDIR /app was created by root, it's owned by root.
# However, COPY --chown handles ownership of copied files.
# The directory /app itself should be writable by appuser if needed at runtime (e.g., for logs if not externalized)
# but for source code, read-only is fine.
COPY --chown=appuser:appgroup . .

# Set default environment variables for configurations
ENV REACT_MCP_LOG_DIR="logs"
ENV REACT_MCP_LOG_LEVEL="INFO"

# Expose port if needed (not required for stdio transport, but in case)
# EXPOSE 3000 - Not needed for stdio server

# Command to run the MCP server using stdio transport
# USER appuser is already set
CMD ["npm", "start"]
